export { default as AuthenModel } from './base/authen.model'
export { default as ProvinceModel } from './base/province.model'
export { default as DistrictModel } from './base/district.model'
export { default as SubDistrictModel } from './base/subDistrict.model'
export { default as AddressModel } from './base/address.model'
export { default as UserModel } from './base/user.model'
export { default as Devicemodel } from './base/device.model'
export { default as DeviceHistoryModel } from './base/devicehistory.model'
export { default as TestModel } from './base/test.model'
export { default as RoleModel } from './base/role.model'
export { default as ExamRoomModel } from './base/exam_room.model'
export { default as QuestTransModel } from './base/quest_trans.model'
export { default as QuestModel } from './base/quest.model'
export { default as CompanyModel } from './base/company.model'
export { default as NumQuestModel} from './base/num_quest.model'
